import Head from 'next/head'
import { useState } from 'react';


export default function Home() {

const [result, setResult] = useState('');

const handleClick = (number) => {
  setResult(result + number);
}

const resetCalc = () => {
  setResult('');
}

const handleClickZero = () => {
  if (result !== '') setResult(result + 0)
}

const handleClickDecimal = () => {
  if (!result.includes(".") && result !== '') setResult(result + ".")
}

const delCalc = () => {
  setResult(result.slice(0,-1));
}

const displayResult = () => {
  return result;
}


  return (
    <div>
      <Head>
        <title>Frontend Mentor | Calculator app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>

      <main className="calculator">
        <h1>calc</h1>
        <div className="screen">
          <p className="screen-text">{result}</p>
        </div>
        <div className="keypad">
          <div className="row-1">
            <button value="7" onClick={e => handleClick(e.target.value)}>7</button>
            <button value="8" onClick={e => handleClick(e.target.value)}>8</button>
            <button value="9" onClick={e => handleClick(e.target.value)}>9</button>
            <button id="var-1" onClick={delCalc}>DEL</button>
          </div>
          
          <div className="row-2">
            <button value="4" onClick={e => handleClick(e.target.value)}>4</button>
            <button value="5" onClick={e => handleClick(e.target.value)}>5</button>
            <button value="6" onClick={e => handleClick(e.target.value)}>6</button>
            <button>+</button>
          </div>

          <div className="row-3">
            <button value="1" onClick={e => handleClick(e.target.value)}>1</button>
            <button value="2" onClick={e => handleClick(e.target.value)}>2</button>
            <button value="3" onClick={e => handleClick(e.target.value)}>3</button>
            <button>-</button>
          </div>

          <div className="row-4">
            <button onClick={handleClickDecimal}>.</button>
            <button onClick={handleClickZero}>0</button>
            <button>/</button>
            <button>x</button>
          </div>
          
          <div className="row-5">
            <button id="var-1" onClick={resetCalc}>RESET</button>
            <button id="var-2">=</button>

          </div>

        </div>
      </main>

      <footer className="attribution">
        Challenge by <a href="https://www.frontendmentor.io?ref=challenge" target="_blank">Frontend Mentor</a>. 
        Coded by <a href="#">Ash</a>.
      </footer>
    </div>
  )
}
